// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2OuloGkWtPbIiGXt6nMNAUVkVdgBePDM',
    appId: '1:654508927394:web:4deb63761585c859dceafb',
    messagingSenderId: '654508927394',
    projectId: 'cursofirebase-18110',
    authDomain: 'cursofirebase-18110.firebaseapp.com',
    databaseURL: 'https://cursofirebase-18110.firebaseio.com',
    storageBucket: 'cursofirebase-18110.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHOVccte3fBJv-KQyq8j5BcBpEwQ7GS1s',
    appId: '1:654508927394:android:3a5483095c8901e1dceafb',
    messagingSenderId: '654508927394',
    projectId: 'cursofirebase-18110',
    databaseURL: 'https://cursofirebase-18110.firebaseio.com',
    storageBucket: 'cursofirebase-18110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ecB47KUTTtdzLZA_KIseAZMh1Uoo0uk',
    appId: '1:654508927394:ios:e2624a4f8d2bdd88dceafb',
    messagingSenderId: '654508927394',
    projectId: 'cursofirebase-18110',
    databaseURL: 'https://cursofirebase-18110.firebaseio.com',
    storageBucket: 'cursofirebase-18110.appspot.com',
    iosClientId: '654508927394-7092kskes7bh5s2pokb2aickqavfl3pn.apps.googleusercontent.com',
    iosBundleId: 'escaner.documentos.pdf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ecB47KUTTtdzLZA_KIseAZMh1Uoo0uk',
    appId: '1:654508927394:ios:489f9c96d53ac090dceafb',
    messagingSenderId: '654508927394',
    projectId: 'cursofirebase-18110',
    databaseURL: 'https://cursofirebase-18110.firebaseio.com',
    storageBucket: 'cursofirebase-18110.appspot.com',
    iosClientId: '654508927394-g2h2cfqs8d0kja43dqrj0jumb0hc4k3g.apps.googleusercontent.com',
    iosBundleId: 'escaner.documentos.pdfScanner',
  );
}
